version: "3"
services:
       visitor-count:
           container_name: visitor-count
           image: visitorcount:local
           restart: always
           build: .
           ports:
             - "3000:3000"
           links:
             - mongo
       mongo:
             container_name: mongo
             image: mongo:5.0.12
             volumes:
               - ./data:/data/db
             ports:
               - '27017:27017'